//fetch
export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";
//delete
export const DELETE_COMMENTS_REQUEST = "DELETE_COMMENTS_REQUEST";
export const DELETE_COMMENTS_SUCCESS = "DELETE_COMMENTS_SUCCESS";
export const DELETE_COMMENTS_FAIL = "DELETE_COMMENTS_FAIL";
//edit
export const EDIT_COMMENTS_REQUEST = "EDIT_COMMENTS_REQUEST";
export const EDIT_COMMENTS_SUCCESS = "EDIT_COMMENTS_SUCCESS";
export const EDIT_COMMENTS_FAIL = "EDIT_COMMENTS_FAIL";